#!/usr/bin/env php
<?php
/*
 * This file is part of the RBot app.
 *
 * (c) Francois Lajoie <o_o@francoislajoie.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * RBot CLI 
 * 
 * ex: rbot.php [app-command] [command-argv]
 * 
 */
namespace App\Commands;
define('NS_APP', __NAMESPACE__.'\\');

require __DIR__.'/rbot/loader.php';

use RBot\RBot;
use RBot\Exception\CommandNotFound;
use App\App;

try {
    RBot::init(RBot::SANDBOX);
    $app = new app();
    $app->run();
}
catch(CommandNotFound $e) {
    echo $e->getMessage();
}

/*$argv = RBot::argv();

//remove rbot.php
array_shift($argv);

if(!empty($argv)) {

    if(substr($argv[0],0,2) === '$' && isset($argv[1])) {
        $classname = 'RBot\Commands\RBotCommand';
    }
    else {
        $cmd = $argv[0];
        $classname = NS_APP.ucfirst($cmd).'\\'.ucfirst($cmd).'Command';
    }

    RBot::init(RBot::SANDBOX);
    RBot::run(new $classname);
}*/