#!/usr/bin/env php
<?php
/*
 * This file is part of the RBot app.
 *
 * (c) Francois Lajoie <o_o@francoislajoie.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * RBot CLI 
 * 
 * ex: rbot.php [app-command] [command-argv]
 * 
 */
namespace App\Commands;
define('NS_APP', __NAMESPACE__.'\\');
define('RBOT_CLI', 1);

require __DIR__.'/rbot/loader.php';

use RBot\RBot;
use RBot\Exception\CommandNotFound;
use App\App;
use Exception;

try {
    RBot::init(RBot::SANDBOX);
    $app = new app();
    $app->run();
}
catch(Exception $e) {
    echo $e->getMessage();
}