#!/usr/bin/env php
<?php
/*
 * This file is part of the RBot app.
 *
 * (c) Francois Lajoie <o_o@francoislajoie.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * RBot CLI 
 * 
 * ex: rbotc [app-command] [command-argv]
 */
namespace App;
define('NS_APP', __NAMESPACE__.'\\');

require __DIR__.'/rbot/loader.php';

use RBot\RBot;
use App\App;
use Exception;

try {
    RBot::init(RBot::SANDBOX);
    $app = new app();
    $app->run();
}
catch(Exception $e) {
    $suffix = (RBot::env() === 'dev') ? get_class($e) : '';
    die($e->getMessage().' "'.$suffix.'"');
}